### ISSUE TITLE
Mixin causes game to crash when entering nether

### ISSUE THREAD

**Issue by crush2021-1** [CleanroomMC/MixinBooter#35]
I initially thought sponge was the problem as that's when the problem began, but after posting on sponge forums I have been pointed in this direction. here is the log from a crash. I am playing tekxit 3.14 on my server and the minecraft version is 1.12.2 if that helps.
https://github.com/crush2021-1/latest-log/blob/7efe42d6b77e1b08390ce35027f581de1232e3a1/latest%20log%20820
mixins.bugfixes.world.chunksaving is what brought me here
I have already changed the config for sponge but it hasn't solved the problem. Let me know if you need anymore info or another log, thanks.

**Comment by ACGaming** [comment]
Looks like features from Universal Tweaks are incompatible with SpongeForge. Please disable `Entity Tracker` under Bugfixes -> Entities and `Chunk Saving` under Bugfixes -> World inside the Universal Tweaks config and try again!

**Comment by crush2021-1** [comment]
Sorry been away. Just applied the changes, but the server still crashed after entering the nether.

**Comment by crush2021-1** [comment]
I should also note that I did try uninstalling Universal tweaks and that didnt solve the problem either.

**Comment by ACGaming** [comment]
Are you able to test without using SpongeForge? Just to rule it out.

**Comment by crush2021-1** [comment]
Ya without sponge forge it works perfectly fine, however I already posted on it regarding sponge but they pointed me here.
Here’s the link to the forum if you want see what we already covered.
https://forums.spongepowered.org/t/just-added-sponge-to-my-tekxit-pi-server-and-it-crashes-every-time-we-go-to-the-nether/42011

**Comment by ACGaming** [comment]
Is there any reason you‘re using a heavily outdated version of SpongeForge? I threw in the [latest version](https://repo.spongepowered.org/repository/maven-releases/org/spongepowered/spongeforge/1.12.2-2838-7.4.8-RC4142/spongeforge-1.12.2-2838-7.4.8-RC4142.jar) into Tekxit and could launch and switch dimensions just fine.

**Comment by crush2021-1** [comment]
I thought i was using the current version Ill try it

**Comment by crush2021-1** [comment]
still crashes in nether

**Comment by ACGaming** [comment]
Odd, won‘t for me.
Do you get an actual crash report? If so, please share it.

**Comment by crush2021-1** [comment]
https://github.com/crush2021-1/latest-log/blob/53738729aca9977ce97d30621ad8bf532939a132/crash%20report%20625
theres a link to the latest crash report, there are also some logs if you would like to see those aswell
