### ISSUE TITLE
Startup crash with Thaumic Fixes

### ISSUE THREAD

**Issue by WolfBV** [CleanroomMC/MixinBooter#37]
!mixinbooter-8.3
Baubles-1.12-1.5.2
Thaumcraft-1.12.2-6.1.BETA26
thaumicfixes-1.0-nolibs

latest.log: https://pastebin.com/XhmWBnkg

crash report: https://pastebin.com/PB228g62

[latest.log](https://github.com/LoliKingdom/MixinBooter/files/11812955/latest.log)

[crash-2023-06-20_22.05.02-client.txt](https://github.com/LoliKingdom/MixinBooter/files/11813017/crash-2023-06-20_22.05.02-client.txt)

Launch, crash.

**Comment by Vapaman** [comment]
Same issue happens here, reported to the author of thaumicfixes too: 
https://www.curseforge.com/minecraft/mc-mods/thaumic-fixes/comments

The author seems to be inactive though it so its probably better to fix it through this side.

**Comment by Rongmario** [comment]
Fixed in dev.
