### ISSUE TITLE
In RAD modpack crashes

### ISSUE THREAD

**Issue by nageih** [CleanroomMC/MixinBooter#47]
In [Roguelike Adventures and Dungeons](https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons/files/4399780) V1.53
when i use the latest mixinbooter,it crashes
when i use mixinbooter 7.X,it doesn't crash
[crash-report](https://pastebin.com/BXDUsECz)
[latest.log](https://pastebin.com/SmFZy6ZQ)

**Comment by Rongmario** [comment]
Duplicate of #34
