### ISSUE TITLE
MixinBooter crashes the client since 8.0 update

### ISSUE THREAD

**Issue by HaHaWTH** [CleanroomMC/MixinBooter#51]
Environment: Windows 7, Azul zulu JDK 8u362

How to reproduce: 
1.Install mod Sledgehammer and TinkersConstruct(also install Mantle)
2.Install mixinbooter 8.4
3.Game crashed while constructing TiC2

All needed files are here: https://paste.gg/p/anonymous/e19495a7d14e440da019a497467b0229
This issus only occurs when I updated MixinBooter, so I report it here.
Mods I am using: [mods.zip](https://github.com/CleanroomMC/MixinBooter/files/12335395/mods.zip)

**Comment by KorewaLidesu** [comment]
Try this
https://github.com/CleanroomMC/MixinBooter/issues/34#issuecomment-1636546792

**Comment by HaHaWTH** [comment]
> Try this
> [#34 (comment)](https://github.com/CleanroomMC/MixinBooter/issues/34#issuecomment-1636546792)

Moved to #34, thx for the advice
