### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [CleanroomMC/MixinBooter#53]
Not really sure if it's the real cause but imma just post it here.

Log: https://mclo.gs/uzY093g
Info like the modlist and version shown inside should be enough.

**Comment by Rongmario** [comment]
Try removing LoliASM and see if it still persists

**Comment by ChromaPIE** [comment]
i've downgraded mixinbooter to 7.1, solves the problem. i wonder which method is considered better as for now?

**Comment by Rongmario** [comment]
Did my suggestion work?

**Comment by ChromaPIE** [comment]
No, not working. Using MB 8.4 without LoliASM, what's even worse is that the game seemed to be ignoring MB, Dependency Missing pop-up was shown. I checked the jar to make sure it's not corrupted.

**Comment by Rongmario** [comment]
Log for that run?

**Comment by ChromaPIE** [comment]
[2023-08-22-4.log.gz](https://github.com/CleanroomMC/MixinBooter/files/12447855/2023-08-22-4.log.gz)
[debug-3.log.gz](https://github.com/CleanroomMC/MixinBooter/files/12447856/debug-3.log.gz)

**Comment by KorewaLidesu** [comment]
![image](https://github.com/CleanroomMC/MixinBooter/assets/24401452/1feea4dc-0f40-423f-9d3c-1d210ac91b5f)
Race condition troll
Put MixinCompat down 1

**Comment by ChromaPIE** [comment]
@KorewaLidesu Here it is, basically just mods and config folder so you can simply create a 1.12.2 instance and drag them in.

**Comment by Rongmario** [comment]
Is this still reproducible? @ChromaPIE @KorewaLidesu

**Comment by ChromaPIE** [comment]
No crash of this kind with the latest version of the mods mentioned. fine for me to just close it.
