### ISSUE TITLE
Can't use the other classloader with mixinbooter

### ISSUE THREAD

**Issue by SettingDust** [CleanroomMC/MixinBooter#54]
`ConfigDecorators` need `Launch.loader` for get mod id. I'm sideloading a mixin service in my own Class Loader for mixin some others.
Can I disable it? Or remove the restrict since any classloader is able to adapt the logic?

**Comment by Rongmario** [comment]
It is meant for mod ids hence why it is pulling resource names from `LaunchClassLoader`. How will you be sideloading another mixin service? What is the usecase?

**Comment by SettingDust** [comment]
> How will you be sideloading another mixin service?

Standalone class loader and a new MixinService

> What is the usecase?

Mixin the bukkit plugins

**Comment by Rongmario** [comment]
I'll make the decorators non-static and decouple the FML elements then, thank you for bringing it up.

**Comment by Noahfrechette** [comment]
any news for fixing this?

**Comment by Rongmario** [comment]
It's being worked on [here](https://github.com/CleanroomMC/UniMix/commit/1497071629e931995fe321e10599a3b6cda07a7e). The API should be finalizing in the next couple of days.

**Comment by Rongmario** [comment]
Should be implemented & fixed in 8.5.
