### ISSUE TITLE
MixinsBooster + Forked Proxy crashed on startup

### ISSUE THREAD

**Issue by 1Mangomaster1** [CleanroomMC/MixinBooter#58]
Forked Proxy: https://www.curseforge.com/minecraft/mc-mods/forked-proxy

Here's the crash report: https://pastebin.com/FjThfAzM

I read the other issues which had very similar crash reports... however, some things they suggested(such as swapping to 7.1) don't solve my problem, I tried swapping many many versions such but it's all the same, the crash happens even with Forked Proxy not installed so I assumed the origin of the problem is with this mod

**Comment by Rongmario** [comment]
I believe the issue is VanillaFix since you mentioned `the crash happens even with Forked Proxy not installed`, and it is incompatible and outdated, consider using [CensoredASM](https://legacy.curseforge.com/minecraft/mc-mods/lolasm).

**Comment by 1Mangomaster1** [comment]
Yeah... I tried it without vanilla fix and it indeed worked, thank you!

**Comment by Rongmario** [comment]
No problem!
