### ISSUE TITLE
Requieres mixinbooter bug

### ISSUE THREAD

**Issue by NuanKi** [CleanroomMC/MixinBooter#61]
i have a mod that needs mixinbooter 8.3 or above, and i have the 8.8 version and when i try to open the game it says:
You must include the right dependencies
Requieres mixinbooter 8.3 or above (missing)
![image](https://github.com/CleanroomMC/MixinBooter/assets/80914838/b84688c1-cda0-4305-88eb-3c94d5ea9166)
while this is my mods folder
![image](https://github.com/CleanroomMC/MixinBooter/assets/80914838/6cde1ba9-30b0-48da-97c7-5150ac51fa12)
i tried reinstalling this and the mod that needs this, but its the same
This is the latest.log
https://pastebin.com/HUh7MNXw

**Comment by KorewaLidesu** [comment]
Have you ask this on Neeve github yet?

**Comment by NuanKi** [comment]
No, it wasnt the only mod that says the same, but lemme ask in the other 3 githubs

**Comment by Rongmario** [comment]
Why 3 other GitHubs?

**Comment by NuanKi** [comment]
bcuz the problem happened with 3 different mods i was trying to add, but i removed 2 before sending the screenshot here

**Comment by NotMyWing** [comment]
![image](https://github.com/CleanroomMC/MixinBooter/assets/22255622/2c1bfd13-dc0a-4a07-92d6-9dbb0c52573c)
Unable to reproduce with just MB, NAE2 and PAE2.

**Comment by NotMyWing** [comment]
Further inspection revealed that it's likely that a mod (most likely Essential) is forcing an older version of Mixin.

```java
Caused by: java.lang.NoSuchFieldError: CLEANROOM_DISABLE_MIXIN_CONFIGS
	at zone.rong.mixinbooter.MixinBooterPlugin.initialize(MixinBooterPlugin.java:97) ~[!mixinbooter-8.8.jar:?]
	at zone.rong.mixinbooter.MixinBooterPlugin.<init>(MixinBooterPlugin.java:30) ~[!mixinbooter-8.8.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) ~[forge-1.12.2-14.23.5.2860.jar:?]
	... 49 more
```

Try removing Essential and see if it helps.

**Comment by NuanKi** [comment]
I'll check it in about 5 hours after I get home

**Comment by NuanKi** [comment]
There is no way to uninstall essentials without deleting your entire .minecraft
The most likely thing is that it is the culprit of the mixin
I guess I'll play with it until the world ends and I'll confirm again if it is or not, after restarting the entire mc

**Comment by ChuyRK** [comment]
Getting the same issue, but it works when I disable just the essential mod file 
https://pastebin.com/JQgakRCq

**Comment by KorewaLidesu** [comment]
> Getting the same issue, but it works when I disable just the essential mod file

Try switch the java to newer version
`[main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\CurseForge\minecraft\Install\runtime\jre-legacy\windows-x64\jre-legacy`

**Comment by Rongmario** [comment]
Why the hell is Essentials overriding the forge installation?

**Comment by NuanKi** [comment]
idk, but since it requires an installer
https://essential.gg/download

**Comment by NuanKi** [comment]
ill try disabling essentials in the mod config, and then installing the neeve mod
