### ISSUE TITLE
Conflict with Essential mod

### ISSUE THREAD

**Issue by littlepianist** [CleanroomMC/MixinBooter#63]
when this mod is installed, essential mod menu will not be shown.

**Comment by hampop** [comment]
> when this mod is installed, essential mod menu will not be shown.

ah i see  mixinbooter 8.9 cause this issue. on 8.8 it is fine so roll back to 8.8

**Comment by Rongmario** [comment]
I won't be supporting the Essential mod as it is closed source and has its own mixin + launching service.

**Comment by viciscat** [comment]
Just putting this here in case someone stumbles upon this issue, as of Essential 1.3.2.6 this has been fixed. Also essential's source is now visible on github
