### ISSUE TITLE
Updated Mixin from 7.1 to 8.8 and got a crash

### ISSUE THREAD

**Issue by Darktotaled** [CleanroomMC/MixinBooter#64]
https://mclo.gs/UyhmOr7

The crash catcher says its a problem with minecraft, forge and industrialcraft 2 but i noticed in the logs that mixin was mentioned and it was the only thing that i changed in this pack. switching back to mixin 7.1 fixes this

**Comment by Rongmario** [comment]
You'd want to use [Alfheim](https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine) as it is an updated Phosphor that works with newer mixin versions.

**Comment by Darktotaled** [comment]
Ill test that, thanks

**Comment by Darktotaled** [comment]
it didnt work. crashed before launching minecraft.

**Comment by Darktotaled** [comment]
https://privatebin.io/?01dc54f6d50422dd#2mEcCUk8xrmmhMQGAkYQDCqLBUV9sCtjU1SiBfbR6YxS
the latest.log

**Comment by Darktotaled** [comment]
@Rongmario pastebin said i had offensive words in my log so i had to use privatebin for that

**Comment by Rongmario** [comment]
Think the mod requires [Red Core](https://www.curseforge.com/minecraft/mc-mods/red-core). Also for the future, use [mc.logs](https://mclo.gs/), it's better for minecraft log/crash files.
