### ISSUE TITLE
The game did not recognize this module (only the log file)

### ISSUE THREAD

**Issue by Mental-annoyance** [CleanroomMC/MixinBooter#66]
I installed this module correctly but it was not recognized (I directly cut and pasted it into a folder after downloading without any other actions)
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/13624495/latest.log)
I'm sorry, becaus the game did not start successfully, I can only get this file.

**Comment by Mental-annoyance** [comment]
After reinstalling the game launcher, the module still cannot be recognized

**Comment by KorewaLidesu** [comment]
Is LiteLoader required to launch the pack?

**Comment by Mental-annoyance** [comment]
I just downloaded and installed LiteLoader, but still haven't resolved this issue.

**Comment by KorewaLidesu** [comment]
> I just downloaded and installed LiteLoader, but still haven't resolved this issue.

Can you remove LiteLoader and try again?

**Comment by Mental-annoyance** [comment]
I have tried again three times, but none of them worked

**Comment by KorewaLidesu** [comment]
Please send the log that you have removed LiteLoader

**Comment by Mental-annoyance** [comment]
I just disabled the problematic mod, and now my game can start normally(BuildCraftRF,NoLocalizationConflict)
[minecraft-exported-logs-2023-12-10T17-27-47.log](https://github.com/CleanroomMC/MixinBooter/files/13627159/minecraft-exported-logs-2023-12-10T17-27-47.log)
This is a successfully launched log
