### ISSUE TITLE
Crash on start Up in 8.8 Version

### ISSUE THREAD

**Issue by javiburatos** [CleanroomMC/MixinBooter#67]
I update 7.1 to 8.8 and my game crash on start up.

Here I post my change log and crash report
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/13708149/latest.log)
[crash-2023-12-18_20.49.47-client.txt](https://github.com/CleanroomMC/MixinBooter/files/13708151/crash-2023-12-18_20.49.47-client.txt)

**Comment by KorewaLidesu** [comment]
`net.minecraftforge.fml.common.MissingModsException: Mod erebusfix (ErebusFix) requires [erebus]`?

**Comment by javiburatos** [comment]
ups sorry, my mistake xd. here I post the corrects files:
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/13713871/latest.log)
[crash-2023-12-19_10.40.02-client.txt](https://github.com/CleanroomMC/MixinBooter/files/13713872/crash-2023-12-19_10.40.02-client.txt)

**Comment by KorewaLidesu** [comment]
Remove VanillaFix and use CensoredASM instead

**Comment by javiburatos** [comment]
ok, it works. Thanks!!!
