### ISSUE TITLE
Minecraft 8.9 Support Broken

### ISSUE THREAD

**Issue by Nolij** [CleanroomMC/MixinBooter#69]
Mod doesn't work on Minecraft 8.9 without adding this library to the classpath:
```json
        {
            "name": "it.unimi.dsi:fastutil:8.5.12"
        }
```

After adding that, I get a dependency error stating I need to install SpongeForge 7.4.8 or greater... on the client. Attempted to do so just to see if it would somehow work and shockingly it did not.

**Comment by Rongmario** [comment]
I misread `Minecraft 8.9` as `MixinBooter 8.9`, you mean Minecraft 1.8.9 right?. I'll fix this for next release.

**Comment by Nolij** [comment]
> I misread `Minecraft 8.9` as `MixinBooter 8.9`, you mean Minecraft 1.8.9 right?. I'll fix this for next release.

Yes, sorry for my phrasing there. Thanks!

**Comment by Nolij** [comment]
I'm still getting the `spongeforge` dependency issue on latest 9.1.
