### ISSUE TITLE
The repo for developers is down and builds are failing

### ISSUE THREAD

**Issue by TherionRO** [CleanroomMC/MixinBooter#70]
Hey! The repo provided on this github is currently down and I cant build my projects which depends on mixinbooter 8.9. Im really sorry if this is a duplicate issue,I checked and I could not find any issues that fixes this. Can you fix the repo so I and the others can use it again,or is there a fix for this which I dont know? Maybe I can download those binaries locally and specify them locally instead of pulling them from a repo?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve zone.rong:mixinbooter:8.9.
     Required by:
         project :
      > Could not resolve zone.rong:mixinbooter:8.9.
         > Could not get resource 'https://maven.cleanroommc.com/zone/rong/mixinbooter/8.9/mixinbooter-8.9.pom'.
            > Could not GET 'https://maven.cleanroommc.com/zone/rong/mixinbooter/8.9/mixinbooter-8.9.pom'.
               > maven.cleanroommc.com: Name or service not known

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 28s

**Comment by Rongmario** [comment]
Give it a few more tries and flush your caches, we've just migrated a few things.
