### ISSUE TITLE
Failed to launch with OptiFine 1.8.8

### ISSUE THREAD

**Issue by HowardZHY** [CleanroomMC/MixinBooter#71]
org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/crash/CrashReport::func_71498_d()Ljava/lang/String; has incompatible changes at opcode 132 in callback mixin.mixinbooter.init.json:CrashReportMixin from mod unknown-owner->@Inject::afterStackTracePopulation(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/io/StringWriter;Ljava/io/PrintWriter;Ljava/lang/Throwable;)V
Expected: [Ljava/io/StringWriter;, Ljava/io/PrintWriter;, Ljava/lang/Throwable;]
Found: [Ljava/io/StringWriter;, Ljava/io/PrintWriter;, Ljava/lang/Object;]
Available: [Ljava/io/StringWriter;, Ljava/io/PrintWriter;, Ljava/lang/Object;, Ljava/lang/String;, Ljava/lang/Throwable;]

https://mclo.gs/dMVwJVY

**Comment by Rongmario** [comment]
I'll disable this mixin in the next release for lower mc versions.
