### ISSUE TITLE
Failed to launch with BetterPortal mod on mixinbooter upper 7.1 version

### ISSUE THREAD

**Issue by Robolightning** [CleanroomMC/MixinBooter#72]
Minecraft 1.12.2
[Mixinbooter 9.1](https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files/5079135) (all versions upper 7.1, but testet on 9.1)
Forge 14.23.5.2860

logs:
[debug.log](https://github.com/CleanroomMC/MixinBooter/files/14489906/debug.log)
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/14489907/latest.log)
[launcher_log.txt](https://github.com/CleanroomMC/MixinBooter/files/14489878/launcher_log.txt)
*I closed Minecraft using the task manager

For comparison, on the same modpack only with mixinbooter 7.1:
[debug.log](https://github.com/CleanroomMC/MixinBooter/files/14489945/debug.log)
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/14489946/latest.log)
[launcher_log.txt](https://github.com/CleanroomMC/MixinBooter/files/14489949/launcher_log.txt)
*I also closed the game after it started using the task manager

Everything works on [Mixinbooter 7.1](https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files/4459218)

**Comment by KorewaLidesu** [comment]
Would you like to put some logs here?

**Comment by Robolightning** [comment]
Ok, I realized that I found the wrong files. I have a large assembly, and I tried to isolate the files that conflict with the mixinbooter. But these particular mods do not launch without it... I will continue the search further using another method, for now I can send the log with the entire assembly, but there are too many files in it, it may not be easy to figure it out
[launcher_log.txt](https://github.com/CleanroomMC/MixinBooter/files/14489821/launcher_log.txt)

**Comment by Robolightning** [comment]
> Would you like to put some logs here? Also, please check this issue #34

I have Just Enough IDs and ErebusFix in my modepack, has it already fixed at the version 9.1?

**Comment by Robolightning** [comment]
I updated the commit and added logs

**Comment by KorewaLidesu** [comment]
Remove BetterPortals for now, I will try ask the author how his mixin applied.
You can only use BetterPortals or OF.

**Comment by Robolightning** [comment]
> You can only use BetterPortals or OF. I will try ask the author how his mixin applied and figure out way to fix it properly

It works (loads), but now it don't see Guide book by Arcane archives

![image](https://github.com/CleanroomMC/MixinBooter/assets/89173189/834e1074-ad5a-4b79-a9d4-d25a33c1d172)
[debug.log](https://github.com/CleanroomMC/MixinBooter/files/14490172/debug.log)
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/14490175/latest.log)
[launcher_log.txt](https://github.com/CleanroomMC/MixinBooter/files/14490176/launcher_log.txt)

**Comment by Robolightning** [comment]
Same error at version 7.1

**Comment by KorewaLidesu** [comment]
It is the mod itself issue.
Seem like they are using wrong modid to check for mod dependency

**Comment by Robolightning** [comment]
> It is the mod itself issue. Seem like they are using wrong modid to check for mod dependency
> 
> Do you have discord? We can discuss about this on the [discord server](https://discord.gg/f2K4aSpG4F) instead

But with BetterPortal mod this error didn't exist. Strange. Yes, I have a Discord, let's continue there

**Comment by Robolightning** [comment]
> It is the mod itself issue. Seem like they are using wrong modid to check for mod dependency
> 
> Do you have discord? We can discuss about this on the [discord server](https://discord.gg/f2K4aSpG4F) instead

You was right, thanks. It was a problem with mod file (Arcane Archives). So, Main problem is BetterPortal
