### ISSUE TITLE
Crash Sponge Forge

### ISSUE THREAD

**Issue by SunriseCat-Dev** [CleanroomMC/MixinBooter#74]
Logs:
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/14524417/latest.log)
[debug.log](https://github.com/CleanroomMC/MixinBooter/files/14524418/debug.log)

How fix this?

**Comment by KorewaLidesu** [comment]
Disable `B:threadPriorityFix` in CensoredASM config

<details>
<summary>Config name</summary>
loliasm.cfg
</details>
