### ISSUE TITLE
Crash MixinBooter 9.1 with VanillaFix

### ISSUE THREAD

**Issue by Robolightning** [CleanroomMC/MixinBooter#79]
VanillaFix: 1.0.10-150
logs:
[debug.log](https://github.com/CleanroomMC/MixinBooter/files/15057579/debug.log)
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/15057580/latest.log)
[crash-2024-04-22_07.19.30-client.txt](https://github.com/CleanroomMC/MixinBooter/files/15057581/crash-2024-04-22_07.19.30-client.txt)

**Comment by MasterEnderman** [comment]
Don't use vanilla fix. It's superseeded by loliasm/censoredasm.

**Comment by Robolightning** [comment]
> Don't use vanilla fix. It's superseeded by loliasm/censoredasm.

Ok, thanks!
