### ISSUE TITLE
Crash MixinBooter 9.1 with MakeZoomZoom

### ISSUE THREAD

**Issue by Robolightning** [CleanroomMC/MixinBooter#80]
MakeZoomZoom version: 0.0.4
Full logs:
[crash-2024-04-22_07.25.28-client.txt](https://github.com/CleanroomMC/MixinBooter/files/15057621/crash-2024-04-22_07.25.28-client.txt)
[debug.log](https://github.com/CleanroomMC/MixinBooter/files/15057630/debug.log)
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/15057631/latest.log)

**Comment by Rongmario** [comment]
MakeZoomZoom is not active and with newer mods such as loliasm / universaltweaks / vintagefix that basically replaces it.
