### ISSUE TITLE
Crashes adter adding Mixinbooster 8.8 and Lootr

### ISSUE THREAD

**Issue by Kiwicast** [CleanroomMC/MixinBooter#82]
Server worked well until I added MixinBooster which was a dependancy of Lootr 1.12.2 Might be a simple fix but unsure of whats going on here.

[
[latest.log](https://github.com/CleanroomMC/MixinBooter/files/15367055/latest.log)
[crash-2024-05-18_23.00.42-server.txt](https://github.com/CleanroomMC/MixinBooter/files/15367056/crash-2024-05-18_23.00.42-server.txt)
](url)

**Comment by Kiwicast** [comment]
seems 7.1 works fine. 8.8 doesnt

**Comment by KorewaLidesu** [comment]
Replace Phosphor with Alfhelm

**Comment by Kiwicast** [comment]
Thanks i will try that

**Comment by Rongmario** [comment]
That should be it, gonna close, if you encounter anything feel free to reopen.
