### ISSUE TITLE
[bug report] Removes essential mod

### ISSUE THREAD

**Issue by vinnyg0621** [CleanroomMC/MixinBooter#86]
so, I also have the essential mod and for some reason after installing this one it got disabled.
<img width="1275" alt="Screenshot 2024-06-12 205950" src="https://github.com/CleanroomMC/MixinBooter/assets/57818441/c8e04b82-df20-4249-b233-b16c1ed165eb">
<img width="429" alt="Screenshot 2024-06-12 210002" src="https://github.com/CleanroomMC/MixinBooter/assets/57818441/b7f1fae7-5245-44b9-b9e0-63f2f96d878d">
the pictures are showing me that I do have it, but for some reason this mod just disables the whole mod.

**Comment by WaitingIdly** [comment]
MixinBooter is not compatible with Essentials, see https://github.com/CleanroomMC/MixinBooter/issues/63
