### ISSUE TITLE
 Compatibility Issue with MC Eternal Modpack and MixinBooter Version 7.2 and Above

### ISSUE THREAD

**Issue by FloT1** [CleanroomMC/MixinBooter#91]
Hello,

I’ve encountered an issue while updating the MC Eternal modpack, specifically with the MixinBooter mod. After upgrading to a version higher than 7.1, the game starts crashing and refuses to launch. To restore stability, I had to revert to version 7.1. However, I recently added a new mod that requires MixinBooter version 8.0 or higher.

Could you please provide guidance on how to resolve this issue and achieve compatibility with the newer version of MixinBooter without causing crashes? Any assistance or recommendations would be greatly appreciated.

Thank you in advance!

**Comment by Rongmario** [comment]
Send your log + crash report, its possibly a phosphor issue if MC Eternal still has that. There is no stability issue but outdated mods.

**Comment by FloT1** [comment]
wow, thank you so much for such a quick reply)

[crash-2024-08-22_23.08.24-client.txt](https://github.com/user-attachments/files/16718222/crash-2024-08-22_23.08.24-client.txt)

**Comment by FloT1** [comment]
I have successfully updated all the mods in my build, only these mods remain unupdated
![image](https://github.com/user-attachments/assets/ab42e170-a4cc-4250-9377-be5e1b625f04)

I also attach the log file:
[2024-07-25-1.log.gz](https://github.com/user-attachments/files/16718794/2024-07-25-1.log.gz)

**Comment by Rongmario** [comment]
Essentials wont work, I've seen you disabled it there but its still enabled from what I can see in the logs.

**Comment by FloT1** [comment]
> Essentials wont work, I've seen you disabled it there but its still enabled from what I can see in the logs.

I had the same problem before installing Essentials

**Comment by Rongmario** [comment]
From what I can see:

VanillaFix (use [CensoredASM](https://www.curseforge.com/minecraft/mc-mods/lolasm) instead)
Phosphor (use [Alfheim](https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine) instead)

**Comment by FloT1** [comment]
I installed the specified mods and disabled the other two. However, a new problem has arisen: when I click 'Play,' Minecraft minimizes, and nothing happens—the modpack doesn't start loading. I have to close it through the Task Manager.

**Comment by Rongmario** [comment]
There should be new logs even if the screen doesn't spawn

**Comment by FloT1** [comment]
> There should be new logs even if the screen doesn't spawn

where do I need to go?

**Comment by Rongmario** [comment]
Doesn't seem like you updated MixinBooter + MixinBootstrap doesn't need to be installed.

**Comment by FloT1** [comment]
> Doesn't seem like you updated MixinBooter + MixinBootstrap doesn't need to be installed.

Thanks, problem solved. apparently it was the MixinBootstrap mod that caused the problem.
