### ISSUE TITLE
Crashes on 1.12.2

### ISSUE THREAD

**Issue by birchyy** [CleanroomMC/MixinBooter#93]
MixinBooter keeps crashing my minecraft upon loading, but without it my minecraft wont load at all.
https://pastebin.com/fFt2dZih this is the log. I dont know anything about crash logs and stuff so any help greatly appreciated

**Comment by Rongmario** [comment]
1. Update your MixinBooter
2. Remove VanillaFix for CensoredASM
3. Remove Foamfix for VintageFix

**Comment by birchyy** [comment]
removing vanilla fix worked, thank u!
