### ISSUE TITLE
Crash with Phosphor mod

### ISSUE THREAD

**Issue by steam9w** [CleanroomMC/MixinBooter#95]
- Mods:
Phosphor mc1.12.2-0.2.7
MixinBooter 9.4

When starting a server with a mod Phosphor, I get an сrash.

https://pastebin.com/D7DQj0Kh

**Comment by Rongmario** [comment]
Use [Alfheim](https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine) instead. Phosphor is outdated.
