### ISSUE TITLE
Mods not detecting when using 10.0

### ISSUE THREAD

**Issue by superJK92iscool** [CleanroomMC/MixinBooter#96]
I am using a mod called CrazyAE  and Neeve's AE2: Extended Life Additions both are AE2 Unofficial Extended Life addons which says it wants mixinbooter 8.3 or above

**Comment by superJK92iscool** [comment]
https://mclo.gs/oUIHSns are the logs

**Comment by Rongmario** [comment]
Essential isn't supported with MixinBooter. Open another issue if it occurs without Essential.
